### ISSUE TITLE
Extensions not reloading

### ISSUE THREAD

**Issue by JeromeDane** [robin-drexler/chrome-extension-auto-reload#1]
This extension does EXACTLY what I need, but when I got everything working, the actual reloading of extensions wasn't happening. Perhaps Chrome changed something recently in an update. I've found a working, open source extension called [Extension Reloader](https://chrome.google.com/webstore/detail/extensions-reloader/fimgfedafeadlieiabdeeaodndnlbhid) that uses a button to do the reloading, and it works. I pulled the [reloadExtensions](https://github.com/arikw/chrome-extensions-reloader/blob/master/background.js#L1) function from there into your code, and now everything is running BEAUTIFULLY. 

See https://github.com/JeromeDane/chrome-extension-auto-reload/commit/7a293bb7d0f6d3fd63a3c3ff37742374702549f4

Will create a pull request shortly.

**Comment by caesarsol** [comment]
+1 for merging!
(the code style is not perfectly coherent though - you used different indentation spacings and so)

**Comment by JeromeDane** [comment]
Sorry about the different spacing. I'll try to keep that more inline with source repo next time.

**Comment by JeromeDane** [comment]
@caesarsol I fixed the styling issues in https://github.com/JeromeDane/chrome-extension-auto-reload/commit/36c3b3e2e28f4428b2382bc603350066a8a28c8f. I've been stuck on a windows machine for the last 7 years at my old job. My new job has me on a mac, and I've discovered the beauty of GitHub's atom editor. :sunglasses:  Much better.

Please let me know if you have any other feedback.

Please merge pull request https://github.com/robin-drexler/chrome-extension-auto-reload/pull/2 to fix this issue. :+1:

**Comment by JeromeDane** [comment]
Update: There are two reload methods available. See: https://github.com/JeromeDane/chrome-extension-auto-reload/commit/3a5d1ab47e980d62122c0f641379b19bad40e240
